import React, { useState } from "react";
import {
  CheckCircle,
  AlertTriangle,
  XCircle,
  TrendingUp,
  Download,
  User,
  Shield,
  FileText,
  Send,
  X,
} from "lucide-react";
import ProgressBar from "./ProgressBar";

const AppraisalStep: React.FC = () => {
  const [approvalDecision, setApprovalDecision] = useState("Approve");
  const [approver, setApprover] = useState("");
  const [approvalAuthority, setApprovalAuthority] = useState("ESG Officer");
  const [finalComments, setFinalComments] = useState("");
  const [showApproverModal, setShowApproverModal] = useState(false);
  const [nextPreparer, setNextPreparer] = useState("");
  const [notificationSent, setNotificationSent] = useState(false);

  const approvalOptions = [
    {
      value: "Approve",
      label: "Approve",
      icon: CheckCircle,
      color: "text-emerald-600",
      activeClass: "bg-emerald-50 border-emerald-200 shadow-sm",
    },
    {
      value: "Approve with Conditions",
      label: "Approve with Conditions",
      icon: AlertTriangle,
      color: "text-amber-600",
      activeClass: "bg-amber-50 border-amber-200 shadow-sm",
    },
    {
      value: "Reject",
      label: "Reject",
      icon: XCircle,
      color: "text-red-600",
      activeClass: "bg-red-50 border-red-200 shadow-sm",
    },
    {
      value: "Escalate",
      label: "Escalate",
      icon: TrendingUp,
      color: "text-purple-600",
      activeClass: "bg-purple-50 border-purple-200 shadow-sm",
    },
  ];

  const authorityLevels = [
    "ESG Officer",
    "Senior Risk Manager",
    "Head of Risk",
    "Chief Risk Officer",
    "Executive Committee",
  ];

  const getDecisionColor = (decision: string) => {
    switch (decision) {
      case "Approve":
        return "bg-emerald-50/50 border-emerald-200";
      case "Approve with Conditions":
        return "bg-amber-50/50 border-amber-200";
      case "Reject":
        return "bg-red-50/50 border-red-200";
      case "Escalate":
        return "bg-purple-50/50 border-purple-200";
      default:
        return "bg-slate-50 border-slate-200";
    }
  };

  const getHeaderColor = (decision: string) => {
    switch (decision) {
      case "Approve":
        return "border-l-4 border-emerald-500";
      case "Approve with Conditions":
        return "border-l-4 border-amber-500";
      case "Reject":
        return "border-l-4 border-red-500";
      case "Escalate":
        return "border-l-4 border-purple-500";
      default:
        return "border-l-4 border-slate-500";
    }
  };

  const downloadApprovalReport = () => {
    const reportData = [
      ["BOI ESRM - Step 5: Appraisal & Conditions Report"],
      ["Generated on:", new Date().toLocaleDateString()],
      [""],
      ["Approval Decision:", approvalDecision],
      ["Approver:", approver || "Not specified"],
      ["Approval Authority Level:", approvalAuthority],
      [""],
      ["Final Comments from Risk Reviewer:"],
      [finalComments || "No comments provided"],
      [""],
      ["Report generated by BOI ESRM Tool"],
    ];

    const csvContent = reportData.map((row) => row.join(",")).join("\n");
    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "Approval_Report.csv";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  const handleSendNotification = () => {
    setNotificationSent(true);
    setTimeout(() => {
      setNotificationSent(false);
      setShowApproverModal(false);
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 transition-colors duration-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="bg-white dark:bg-slate-800 rounded-lg shadow-sm border border-slate-200 dark:border-slate-700">
          {/* Header */}
          <div className="border-b border-slate-200 dark:border-slate-700 bg-slate-900 px-6 py-5 rounded-t-lg">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold text-white flex items-center gap-2">
                  <Shield className="w-6 h-6 text-[#FDB913]" />
                  Step 5: Appraisal & Conditions
                </h1>
                <p className="text-slate-300 mt-1 text-sm">
                  Summarize E&S risk, define approval decision, conditions, and
                  obtain sign-off.
                </p>
              </div>
              <button
                onClick={() => setShowApproverModal(true)}
                className="px-4 py-2 bg-[#FDB913] hover:bg-yellow-500 text-slate-900 rounded-md transition-colors flex items-center gap-2 font-medium text-sm shadow-sm"
              >
                <User className="w-4 h-4" />
                Select Next Preparer
              </button>
            </div>
          </div>

          <div className="p-6 space-y-8">
            <ProgressBar currentStep={5} />

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Left Column: Decision Form */}
              <div className="lg:col-span-2 space-y-6">
                {/* Approval Decision Section */}
                <div
                  className={`bg-white dark:bg-slate-800 rounded-lg border shadow-sm overflow-hidden ${getHeaderColor(approvalDecision)} border-slate-200 dark:border-slate-700`}
                >
                  <div className="bg-slate-50 dark:bg-slate-800/50 px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex items-center gap-3">
                    <CheckCircle className="w-5 h-5 text-slate-500" />
                    <h3 className="font-bold text-lg text-slate-900 dark:text-white">
                      Approval Decision
                    </h3>
                  </div>

                  <div
                    className={`p-6 transition-colors duration-300 ${getDecisionColor(approvalDecision)} bg-opacity-30 dark:bg-opacity-10`}
                  >
                    <div className="space-y-6">
                      <div>
                        <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-4">
                          Final decision from the ESRM review
                        </label>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                          {approvalOptions.map((option) => {
                            const Icon = option.icon;
                            const isSelected =
                              approvalDecision === option.value;
                            return (
                              <label
                                key={option.value}
                                className={`
                                  flex items-center gap-3 cursor-pointer p-3 rounded-lg border transition-all
                                  ${
                                    isSelected
                                      ? `${option.activeClass} dark:bg-opacity-20`
                                      : "border-slate-200 dark:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-700/50"
                                  }
                                `}
                              >
                                <input
                                  type="radio"
                                  name="approvalDecision"
                                  value={option.value}
                                  checked={isSelected}
                                  onChange={(e) =>
                                    setApprovalDecision(e.target.value)
                                  }
                                  className="w-4 h-4 text-[#FDB913] border-slate-300 focus:ring-[#FDB913]"
                                />
                                <Icon className={`w-5 h-5 ${option.color}`} />
                                <span
                                  className={`text-sm font-medium ${isSelected ? "text-slate-900 dark:text-white" : "text-slate-600 dark:text-slate-400"}`}
                                >
                                  {option.label}
                                </span>
                              </label>
                            );
                          })}
                        </div>
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                          <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                            Approver Name / Committee
                          </label>
                          <input
                            type="text"
                            value={approver}
                            onChange={(e) => setApprover(e.target.value)}
                            className="w-full px-4 py-2.5 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-[#FDB913] focus:border-transparent bg-white dark:bg-slate-800 text-slate-900 dark:text-white"
                            placeholder="e.g. John Doe"
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                            Approval Authority Level
                          </label>
                          <div className="relative">
                            <select
                              value={approvalAuthority}
                              onChange={(e) =>
                                setApprovalAuthority(e.target.value)
                              }
                              className="w-full px-4 py-2.5 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-[#FDB913] focus:border-transparent appearance-none bg-white dark:bg-slate-800 text-slate-900 dark:text-white pr-10"
                            >
                              {authorityLevels.map((level) => (
                                <option key={level} value={level}>
                                  {level}
                                </option>
                              ))}
                            </select>
                            <div className="absolute inset-y-0 right-0 flex items-center px-3 pointer-events-none text-slate-500">
                              <svg
                                className="w-4 h-4"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                              >
                                <path
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth={2}
                                  d="M19 9l-7 7-7-7"
                                />
                              </svg>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Final Comments Section */}
                <div className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden">
                  <div className="bg-slate-50 dark:bg-slate-800/50 px-6 py-4 border-b border-slate-100 dark:border-slate-700 flex items-center gap-3">
                    <FileText className="w-5 h-5 text-slate-500" />
                    <h3 className="font-bold text-lg text-slate-900 dark:text-white">
                      Final Comments & Rationale
                    </h3>
                  </div>
                  <div className="p-6">
                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-3">
                      Reviewer Comments
                    </label>
                    <textarea
                      value={finalComments}
                      onChange={(e) => setFinalComments(e.target.value)}
                      rows={6}
                      className="w-full px-4 py-3 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-[#FDB913] focus:border-transparent text-slate-900 dark:text-white bg-white dark:bg-slate-800 resize-none"
                      placeholder="Enter final comments, specific conditions, or rationale for the decision..."
                    />
                    <div className="mt-4 flex justify-end">
                      <button
                        onClick={downloadApprovalReport}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-slate-900 dark:bg-slate-700 hover:bg-slate-800 dark:hover:bg-slate-600 text-white rounded-md transition-colors text-sm font-medium"
                      >
                        <Download className="w-4 h-4" />
                        Download PDF Report
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* Right Column: Summary */}
              <div className="lg:col-span-1">
                <div className="bg-slate-50 dark:bg-slate-800/50 rounded-lg border border-slate-200 dark:border-slate-700 p-6 sticky top-6">
                  <div className="flex items-center gap-3 mb-6">
                    <Shield className="w-6 h-6 text-[#FDB913]" />
                    <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                      Appraisal Summary
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Decision
                      </span>
                      <div
                        className={`text-lg font-bold ${
                          approvalDecision === "Approve"
                            ? "text-emerald-600"
                            : approvalDecision === "Reject"
                              ? "text-red-600"
                              : approvalDecision === "Escalate"
                                ? "text-purple-600"
                                : "text-amber-600"
                        }`}
                      >
                        {approvalDecision}
                      </div>
                    </div>

                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Authority
                      </span>
                      <div className="text-slate-900 dark:text-white font-medium">
                        {approvalAuthority}
                      </div>
                    </div>

                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Approver
                      </span>
                      <div className="text-slate-900 dark:text-white font-medium">
                        {approver || "Pending..."}
                      </div>
                    </div>

                    <div className="p-4 bg-white dark:bg-slate-800 rounded-md border border-slate-100 dark:border-slate-700 shadow-sm">
                      <span className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">
                        Date
                      </span>
                      <div className="text-slate-900 dark:text-white font-medium">
                        {new Date().toLocaleDateString()}
                      </div>
                    </div>
                  </div>

                  <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-700">
                    <button className="w-full py-2.5 bg-[#FDB913] hover:bg-yellow-500 text-slate-900 font-bold rounded-lg shadow-md transition-all flex items-center justify-center gap-2">
                      <CheckCircle className="w-5 h-5" />
                      Finalize Appraisal
                    </button>
                    <p className="text-xs text-center text-slate-500 mt-3">
                      This will lock the appraisal and notify stakeholders.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Next Preparer Modal */}
      {showApproverModal && (
        <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-800 rounded-lg shadow-xl w-full max-w-md border border-slate-200 dark:border-slate-700 overflow-hidden transform transition-all">
            <div className="bg-slate-900 p-4 border-b border-[#FDB913] flex justify-between items-center">
              <h3 className="font-bold text-white flex items-center gap-2">
                <User className="w-5 h-5 text-[#FDB913]" />
                Select Next Preparer
              </h3>
              <button
                onClick={() => setShowApproverModal(false)}
                className="text-slate-400 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="p-6">
              {!notificationSent ? (
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-2">
                      Assign to
                    </label>
                    <select
                      value={nextPreparer}
                      onChange={(e) => setNextPreparer(e.target.value)}
                      className="w-full px-3 py-2 border border-slate-300 dark:border-slate-600 rounded-lg focus:ring-2 focus:ring-[#FDB913] focus:border-transparent bg-white dark:bg-slate-800 text-slate-900 dark:text-white"
                    >
                      <option value="">Select a user...</option>
                      <option value="user1">Sarah Connor (Risk Manager)</option>
                      <option value="user2">John Smith (Credit Officer)</option>
                      <option value="user3">Emily Chen (ESG Specialist)</option>
                    </select>
                  </div>

                  <div className="bg-slate-50 dark:bg-slate-900/50 p-3 rounded-md border border-slate-200 dark:border-slate-800">
                    <div className="flex gap-2">
                      <div className="shrink-0 text-slate-600 dark:text-slate-400">
                        <User className="w-5 h-5" />
                      </div>
                      <p className="text-sm text-slate-600 dark:text-slate-400">
                        The selected user will be notified via email and
                        dashboard notification.
                      </p>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="py-8 text-center">
                  <div className="w-16 h-16 bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mx-auto mb-4">
                    <CheckCircle className="w-8 h-8 text-emerald-600 dark:text-emerald-400" />
                  </div>
                  <h4 className="text-lg font-bold text-slate-900 dark:text-white mb-2">
                    Notification Sent!
                  </h4>
                  <p className="text-slate-600 dark:text-slate-400">
                    The next preparer has been notified successfully.
                  </p>
                </div>
              )}
            </div>

            <div className="px-6 py-4 bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-700 flex justify-end gap-3">
              {!notificationSent && (
                <>
                  <button
                    onClick={() => setShowApproverModal(false)}
                    className="px-4 py-2 text-slate-700 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800 rounded-md transition-colors font-medium text-sm"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleSendNotification}
                    disabled={!nextPreparer}
                    className={`
                      px-4 py-2 rounded-md transition-colors font-medium text-sm flex items-center gap-2
                      ${
                        !nextPreparer
                          ? "bg-slate-300 dark:bg-slate-700 text-slate-500 cursor-not-allowed"
                          : "bg-[#FDB913] hover:bg-yellow-500 text-slate-900 shadow-sm"
                      }
                    `}
                  >
                    <Send className="w-4 h-4" />
                    Send Notification
                  </button>
                </>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AppraisalStep;
