import {
  Box,
  Typography,
  Paper,
  Button,
  useTheme,
  alpha,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  IconButton,
} from "@mui/material";
import ScenarioLayout from "./layout/ScenarioLayout";
import { GCB_COLORS } from "@/config/colors.config";
import { Download, Eye, FileText, Filter } from "lucide-react";
import {
  useScenarioStore,
  type ScenarioRunResults,
} from "@/store/scenarioStore";

export default function ScenarioReports() {
  const theme = useTheme();
  const { results } = useScenarioStore();

  const handleDownloadJSON = (data: ScenarioRunResults) => {
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    const timestamp = new Date().getTime();
    link.download = `scenario-result-${data.scenario}-${timestamp}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const STATIC_REPORTS = [
    {
      id: "RPT-2026-001",
      name: "Q1 2026 Climate Stress Test - Executive Summary",
      type: "PDF",
      date: "Feb 02, 2026",
      scenario: "Orderly Transition (NGFS)",
      generatedBy: "System",
      rawData: null,
    },
    {
      id: "RPT-2026-002",
      name: "Portfolio Vulnerability Heatmap - Detailed Data",
      type: "CSV",
      date: "Feb 02, 2026",
      scenario: "Orderly Transition (NGFS)",
      generatedBy: "System",
      rawData: null,
    },
    {
      id: "RPT-2026-003",
      name: "Disorderly Transition - Credit Loss Projections",
      type: "PDF",
      date: "Jan 28, 2026",
      scenario: "Disorderly",
      generatedBy: "Kwame Mensah",
      rawData: null,
    },
    {
      id: "RPT-2026-004",
      name: "Collateral Valuation Impact Report",
      type: "XLSX",
      date: "Jan 15, 2026",
      scenario: "Hot House World",
      generatedBy: "ESG Dept",
      rawData: null,
    },
    {
      id: "RPT-2025-099",
      name: "2025 Annual ESG Risk Disclosure (Pillar 3)",
      type: "PDF",
      date: "Dec 31, 2025",
      scenario: "Multiple",
      generatedBy: "System",
      rawData: null,
    },
  ];

  const generatedReports = results.map((r, i) => ({
    id: `GEN-${i}-${r.timestamp}`,
    name: `${r.scenario.charAt(0).toUpperCase() + r.scenario.slice(1)} Scenario Analysis (${r.horizon})`,
    type: "JSON",
    date: new Date(r.timestamp).toLocaleDateString(),
    scenario: r.scenario.replace(/_/g, " "),
    generatedBy: "User",
    rawData: r,
  }));

  const allReports = [...generatedReports, ...STATIC_REPORTS];

  return (
    <ScenarioLayout>
      <Box
        sx={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          mb: 4,
        }}
      >
        <Box>
          <Typography
            variant="h4"
            fontWeight={800}
            sx={{ color: GCB_COLORS.slate.dark, mb: 1 }}
          >
            Stress Test Reports
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Access generated reports, regulatory exports, and raw data
            downloads.
          </Typography>
        </Box>
        <Button
          variant="outlined"
          startIcon={<Filter size={18} />}
          sx={{ color: GCB_COLORS.slate.DEFAULT }}
        >
          Filter Results
        </Button>
      </Box>

      <Paper
        elevation={0}
        sx={{
          borderRadius: "12px",
          border: `1px solid ${theme.palette.divider}`,
          overflow: "hidden",
        }}
      >
        <TableContainer>
          <Table>
            <TableHead sx={{ bgcolor: alpha(GCB_COLORS.slate.DEFAULT, 0.05) }}>
              <TableRow>
                <TableCell sx={{ fontWeight: 700 }}>Report Name</TableCell>
                <TableCell sx={{ fontWeight: 700 }}>Scenario</TableCell>
                <TableCell sx={{ fontWeight: 700 }}>Type</TableCell>
                <TableCell sx={{ fontWeight: 700 }}>Date Created</TableCell>
                <TableCell sx={{ fontWeight: 700 }}>Generated By</TableCell>
                <TableCell align="right" sx={{ fontWeight: 700 }}>
                  Actions
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {allReports.map((row) => (
                <TableRow key={row.id} hover>
                  <TableCell>
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: 1.5,
                      }}
                    >
                      <FileText size={18} color={GCB_COLORS.slate.DEFAULT} />
                      <Typography variant="body2" fontWeight={600}>
                        {row.name}
                      </Typography>
                    </Box>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" color="text.secondary">
                      {row.scenario}
                    </Typography>
                  </TableCell>
                  <TableCell>
                    <Chip
                      label={row.type}
                      size="small"
                      sx={{
                        fontWeight: 700,
                        fontSize: "0.7rem",
                        height: 24,
                        bgcolor:
                          row.type === "PDF"
                            ? alpha(GCB_COLORS.error, 0.1)
                            : row.type === "CSV"
                              ? alpha(GCB_COLORS.success, 0.1)
                              : alpha(GCB_COLORS.info, 0.1),
                        color:
                          row.type === "PDF"
                            ? GCB_COLORS.error
                            : row.type === "CSV"
                              ? GCB_COLORS.success
                              : GCB_COLORS.info,
                      }}
                    />
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2">{row.date}</Typography>
                  </TableCell>
                  <TableCell>
                    <Typography variant="body2" color="text.secondary">
                      {row.generatedBy}
                    </Typography>
                  </TableCell>
                  <TableCell align="right">
                    <Box
                      sx={{
                        display: "flex",
                        justifyContent: "flex-end",
                        gap: 1,
                      }}
                    >
                      <IconButton
                        size="small"
                        sx={{ color: GCB_COLORS.slate.DEFAULT }}
                      >
                        <Eye size={18} />
                      </IconButton>
                      <IconButton
                        size="small"
                        sx={{ color: GCB_COLORS.gold.dark }}
                        onClick={() =>
                          row.type === "JSON" && row.rawData
                            ? handleDownloadJSON(row.rawData)
                            : null
                        }
                      >
                        <Download size={18} />
                      </IconButton>
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Paper>
    </ScenarioLayout>
  );
}
