export interface MaterialTopic {
  id: string;
  name: string;
  description: string;
  dataNeeds: string[];
  status: "data-driven" | "partial" | "required";
  selected: boolean;
  isCustom?: boolean;
}

export interface MetricInput {
  id: string;
  topicId: string;
  metric: string;
  value: string | number;
  unit: string;
  period: string;
  notes?: string;
}

/** Chart type to render for a topic dashboard */
export type ChartType = "bar" | "pie" | "line" | "horizontal-bar";

/** Describes a chart to generate from metric inputs */
export interface TopicChartConfig {
  title: string;
  type: ChartType;
  dataKey: string;
  color?: string;
}

export const MOCK_TOPICS: MaterialTopic[] = [
  {
    id: "sustainable_finance",
    name: "Sustainable Finance & Investing",
    description:
      "Tracks financing supporting sustainable outcomes and green initiatives.",
    dataNeeds: [
      "Green Loans Volume",
      "Sustainability-linked Deals",
      "% Portfolio ESG Screened",
    ],
    status: "data-driven",
    selected: true,
  },
  {
    id: "climate_change",
    name: "Impacts of Climate Change",
    description:
      "Assessment of physical and transition risks on operations and portfolio.",
    dataNeeds: [
      "Scope 1 & 2 Emissions",
      "Scope 3 Financed Emissions",
      "Climate Risk Exposure",
    ],
    status: "partial",
    selected: true,
  },
  {
    id: "esdd",
    name: "Environmental & Social Due Diligence (ESDD)",
    description:
      "Processes for evaluating environmental and social risks in lending.",
    dataNeeds: [
      "Deals Assessed for E&S Risk",
      "High Risk Transactions",
      "ESDD Training Hours",
    ],
    status: "required",
    selected: false,
  },
  {
    id: "social_impact",
    name: "Social & Economic Impact",
    description:
      "Measuring the broader social and economic value generated by bank activities.",
    dataNeeds: [
      "Jobs Created/Supported",
      "SME Lending Volume",
      "Community Investment",
    ],
    status: "data-driven",
    selected: false,
  },
  {
    id: "financial_inclusion",
    name: "Financial Inclusion & Capacity Building",
    description:
      "Initiatives to expand access to financial services and improve financial literacy.",
    dataNeeds: [
      "Unbanked Accounts Opened",
      "Financial Literacy Reach",
      "MSME Support Programs",
    ],
    status: "partial",
    selected: false,
  },
  {
    id: "customer_experience",
    name: "Customer & Stakeholder Experience",
    description:
      "Ensuring high quality service and engagement with all stakeholders.",
    dataNeeds: [
      "Customer Satisfaction Score",
      "Net Promoter Score",
      "Stakeholder Events",
    ],
    status: "data-driven",
    selected: false,
  },
  {
    id: "employee_dei",
    name: "Employee Engagement, Diversity & Inclusion",
    description: "Fostering a diverse, inclusive, and engaged workforce.",
    dataNeeds: [
      "Employee Engagement Score",
      "Gender Diversity Ratio",
      "Inclusion Index",
    ],
    status: "partial",
    selected: false,
  },
  {
    id: "talent_management",
    name: "Talent Management",
    description:
      "Strategies for attracting, developing, and retaining top talent.",
    dataNeeds: [
      "Training Hours per Employee",
      "Retention Rate",
      "Internal Promotion Rate",
    ],
    status: "data-driven",
    selected: false,
  },
  {
    id: "business_ethics",
    name: "Business Ethics",
    description:
      "Adherence to ethical standards, anti-corruption, and compliance.",
    dataNeeds: [
      "Code of Conduct Breaches",
      "Whistleblower Reports",
      "Compliance Training %",
    ],
    status: "required",
    selected: false,
  },
  {
    id: "systemic_risk",
    name: "Systemic Risk Management",
    description:
      "Managing risks that could trigger instability in the financial system.",
    dataNeeds: [
      "Capital Adequacy Ratio",
      "Liquidity Coverage Ratio",
      "Systemic Risk Stress Tests",
    ],
    status: "data-driven",
    selected: false,
  },
  {
    id: "data_privacy",
    name: "Data Privacy & Cyber Security",
    description:
      "Protecting customer data and ensuring resilience against cyber threats.",
    dataNeeds: [
      "Data Breaches",
      "Cybersecurity Incidents",
      "Data Protection Audits",
    ],
    status: "required",
    selected: true,
  },
  {
    id: "impact_communication",
    name: "Impact Communication",
    description:
      "Transparent reporting and communication of ESG impacts to stakeholders.",
    dataNeeds: [
      "Sustainability Reports",
      "Disclosure Rating",
      "Stakeholder Feedback",
    ],
    status: "partial",
    selected: false,
  },
];
